config/routes.rb
Rails.application.routes.draw do
  resources :scans

  devise_for :users
  scope '/admin' do
    resources :users, as: 'users'
  end

  root to: 'home#index'

end

app/models/scan.rb
class Scan < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: false
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  before_action :set_scan, only: [:show, :edit, :update, :destroy]

  # GET /scans
  # GET /scans.json
  def index
    @scans = Scan.all
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
  end

  # GET /scans/new
  def new
    @scan = Scan.new
  end

  # GET /scans/1/edit
  def edit
  end

  # POST /scans
  # POST /scans.json
  def create
    @scan = Scan.new(scan_params)

    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, notice: 'Scan was successfully created.' }
        format.json { render :show, status: :created, location: @scan }
      else
        format.html { render :new }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scans/1
  # PATCH/PUT /scans/1.json
  def update
    respond_to do |format|
      if @scan.update(scan_params)
        format.html { redirect_to @scan, notice: 'Scan was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan }
      else
        format.html { render :edit }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    @scan.destroy
    respond_to do |format|
      format.html { redirect_to scans_url, notice: 'Scan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan
      @scan = Scan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_params
      params.require(:scan).permit(:url, :type, :content, :last_visited)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
!!!
%html(ng-app="getmoto")
  %head
    %title #{"getmoto".capitalize}
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0")
    -# android stand alone mode
    %meta(name="mobile-web-app-capable" content="yes")
    %link(rel="icon" sizes="192x192" href="/assets/icon.png")
    -# iOS stand alone mode
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="black")
    %link(rel="apple-touch-icon" href="/assets/icon.png")
    %link(rel="apple-touch-startup-image" href="/assets/icon.png")
    -# windows 8.1, maybe mobile, maybe not
    %meta(name="application-name" content="ID Pickup")
    %meta(name="msapplication-navbutton-color" content="#FF3300")
    %meta(name="msapplication-square150x150logo" content="assets/icon.png")
    %meta(name="msapplication-square310x310logo" content="assets/icon.png")
    %meta(name="msapplication-square70x70logo" content="assets/icon.png")
    %meta(name="msapplication-wide310x150logo" content="assets/icon.png")
    %meta(name="msapplication-TileColor" content="#FF3300")
    %meta(name="msapplication-TileImage" content="assets/icon.png")
    %meta(name="msapplication-tooltip" content="ID Pickup")
    -# 
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    -# If you need something from the Ruby code, set it up here
    -# %script
  %body(role="document")
    %div.full_height(ng-view)
      %h1(style="margin-top: 10px;")=t :'Please wait' # Please wait while the application loads!
    = javascript_include_tag 'app'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{'getmoto'.capitalize}
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0")
    -# android stand alone mode
    %meta(name="mobile-web-app-capable" content="yes")
    %link(rel="icon" sizes="192x192" href="/assets/icon.png")
    -# iOS stand alone mode
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="black")
    %link(rel="apple-touch-icon" href="/assets/icon.png")
    %link(rel="apple-touch-startup-image" href="/assets/icon.png")
    -# windows 8.1, maybe mobile, maybe not
    %meta(name="application-name" content="ID Pickup")
    %meta(name="msapplication-navbutton-color" content="#FF3300")
    %meta(name="msapplication-square150x150logo" content="assets/icon.png")
    %meta(name="msapplication-square310x310logo" content="assets/icon.png")
    %meta(name="msapplication-square70x70logo" content="assets/icon.png")
    %meta(name="msapplication-wide310x150logo" content="assets/icon.png")
    %meta(name="msapplication-TileColor" content="#FF3300")
    %meta(name="msapplication-TileImage" content="assets/icon.png")
    %meta(name="msapplication-tooltip" content="ID Pickup")
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.navbar-static-top.navbar-inverse(role="navigation")
        .container-fluid
          .navbar-header.pull-left
            %a.navbar-brand(href="#")
              =image_tag "logo.png", height: '20'
              #{'getmoto'.capitalize}
        -#
          -# Sticky menu, on the right
          #navbar-steady.navbar-header.pull-right
            %ul.nav.navbar-nav.pull-left
              -# Static menu items
              %li.pull-left.hidden-xs
                %a(href="#") Static 1
              -# notice that the first to pull right will be right most!
              %li.pull-right
                %a(href="#") Static 2
              -# Static text, like the username
              %li.navbar-text.pull-right
                %span.hidden-xs Welcome, 
                %span guest
            -# following button should ALWAYS be there, unless there is no colapsable items
            %button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar")
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          #navbar.navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li.active
                %a(href="#") Left 1
              %li
                %a(href="#") Left 2
              %li
                %a.dropdown-toggle(href="#" data-toggle="dropdown")
                  Drop
                  %span.caret
                %ul.dropdown-menu(role="menu")
                  %li.dropdown-header Header for submenu group
                  %li
                    %a(href="#") Submenu 1
                  %li
                    %a(href="#") Submenu 2
                  %li
                    %a(href="#") Submenu 3
                  %li.divider
                  %li.dropdown-header Header for others
                  %li
                    %a(href="#") Submenu 4
                  %li
                    %a(href="#") Submenu 5
            %ul.nav.navbar-nav.navbar-right
              %li
                %a(href="#") Right 1
              %li
                %a(href="#") Right 2
      -#.alert.alert-success(role="alert")=success_notice
      -if notice
        .alert.alert-info(role="alert")=notice
      -#.alert.alert-warning(role="alert")=alert_warning
      -if alert
        .alert.alert-danger(role="alert")=alert
      = yield

app/views/scans/_form.html.haml
= form_for @scan do |f|
  - if @scan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@scan.errors.count, "error")} prohibited this scan from being saved:"
      %ul
        - @scan.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :last_visited
    = f.datetime_select :last_visited
  .actions
    = f.submit 'Save'

app/views/scans/edit.html.haml
%h1 Editing scan

= render 'form'

= link_to 'Show', @scan
\|
= link_to 'Back', scans_path

app/views/scans/index.html.haml
%h1 Listing scans

%table
  - @scans.each do |scan|
    %tr
      %td= link_to scan.url, scan 
      %td= scan.type
      %td= scan.last_visited
      %td= link_to 'Edit', edit_scan_path(scan)
      %td= link_to 'Destroy', scan, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Scan', new_scan_path

app/views/scans/new.html.haml
%h1 New scan

= render 'form'

= link_to 'Back', scans_path

app/views/scans/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @scan.url
%p
  %b Type:
  = @scan.type
%p
  %b Content:
  = @scan.content.html_safe
%p
  %b Last visited:
  = @scan.last_visited

= link_to 'Edit', edit_scan_path(@scan)
\|
= link_to 'Back', scans_path

app/views/users/_form.html.haml
= bootstrap_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation.alert.alert-danger
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    
    = f.text_field :name
  .field
    
    = f.text_field :email
  .field
    
    = f.password_field :password
  .field
    
    = f.password_field :password_confirmation
  .field
    
    = f.check_box :admin
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th Password
    %th Password confirmation
    %th Admin
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.password
      %td= user.password_confirmation
      %td= user.admin
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password
%p
  %b Password confirmation:
  = @user.password_confirmation
%p
  %b Admin:
  = @user.admin

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path